### ISSUE TITLE
Missing networkAccess Field

### ISSUE THREAD

**Issue by akbarbmirza** [zendyani/figma-image-compression#2]
Hey @zendyani - it looks like your plugin makes network requests to a single domain (skimmed the codebase) - is that correct?. It's currently listed as Unknown Network Access on it's Figma Community Page. You can specify what kind of network access your plugin requires using instructions from the docs here: https://www.figma.com/plugin-docs/making-network-requests/#specify-network-access

By defining access to necessary domains, you can increase trust among security-conscious users and organization admins. This is especially important for organizations that require admin approval for plugins/widget.

**Comment by zendyani** [comment]
Thanks @akbarbmirza for the heads up! I've added allowedDomains.
Now you can see on the Figma Community Page which domain is called and why.
